services:
  # 1. MongoDB
  mongodb:
    image: mongo:latest
    container_name: budget-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - budget-network
    restart: always

  # 1.1. MongoDB UI (Mongo Express)
  mongo-express:
    image: mongo-express:latest
    container_name: budget-mongo-ui
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      # Lớp bảo mật thứ 2 cho trang Web UI
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_BASICAUTH_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - budget-network
    restart: always

  # 2. Backend (Hot Reload qua Volume)
  backend:
    build: ./backend
    container_name: budget-backend
    ports:
      - "5000:5000"
    environment:
      # Sửa URI để lấy biến từ .env
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - budget-network
    restart: always

  # 3. Frontend (Hot Reload qua Volume)
  frontend:
    build: ./frontend
    container_name: budget-frontend
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - budget-network
    restart: always

  # 4. Tự động Backup hàng ngày (Phao cứu sinh)
  mongo-backup:
    image: mongo:latest
    container_name: budget-mongo-backup
    restart: always
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_ROOT_USER}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD}
      - MONGO_DB=${MONGO_DB_NAME}
    volumes:
      - ./backups:/backup
    depends_on:
      - mongodb
    networks:
      - budget-network
    # Script tự động backup mỗi 24h và xóa file cũ trên 14 ngày
    entrypoint: >
      sh -c '
      while true; do
        echo "--- Bắt đầu sao lưu lúc $$(date) ---"
        FILE_NAME="/backup/budget-db-backup-$$(date +%Y-%m-%d-%H-%M-%S).gz"
        mongodump --host $$MONGO_HOST --username $$MONGO_USER --password $$MONGO_PASS --db $$MONGO_DB --archive=$$FILE_NAME --gzip --authenticationDatabase admin
        if [ $$? -eq 0 ]; then
          echo "✅ Sao lưu thành công: $$FILE_NAME"
          find /backup -name "budget-db-backup-*" -mtime +14 -delete
        else
          echo "❌ Lỗi: Không thể sao lưu dữ liệu!"
        fi
        sleep 86400
      done'

volumes:
  mongo-data:

networks:
  budget-network:
    driver: bridge
